language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  - SYMFONY_VERSION=2.8.* SYMFONY_ENV=travis

services:
  - mysql

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer install
  - php app/console doctrine:database:create --env=travis
  - php app/console doctrine:migrations:migrate --env=travis --no-interaction

script: phpunit --coverage-text --configuration app/phpunit.travis.xml
