language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate --no-interaction

script: phpunit --coverage-text --configuration app/phpunit.xml.dist
