language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.0

install:
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:migrations:migrate