language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  - SYMFONY_VERSION=2.8.*

services:
  - mysql

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:migrations:migrate --no-interaction
  - php app/console doctrine:migrations:migrate --env=test --no-interaction

script: phpunit --coverage-text --configuration app/phpunit.travist.xml
